server: 
  port: 8060

logging:
  level:
    '[org.springframework]': DEBUG


spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
   url: jdbc:h2:mem:testdb
  mvc:
   hiddenmethod:
    filter:
     enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        